version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      gunicorn config.wsgi:application
      --bind 0.0.0.0:8000
      --workers ${GUNICORN_WORKERS:-3}
      --threads ${GUNICORN_THREADS:-2}
      --timeout ${GUNICORN_TIMEOUT:-30}
      --access-logfile -
      --error-logfile -
      --log-level ${GUNICORN_LOG_LEVEL:-info}
    volumes:
      - static_volume:/usr/src/tbull/static
    expose:
      - "8000"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:13.4
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DATABASE_NAME:-postgres}
      - POSTGRES_USER=${DATABASE_USER:-postgres}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:?Please set DATABASE_PASSWORD in .env}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  nginx:
    image: nginx:1.21.6
    restart: always
    ports:
      - "80:80"
#      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/usr/src/tbull/static
#       - ./certificates:/etc/ssl/certs
#       - ./certificates:/etc/ssl/private
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
