# Generated by Django 5.1.3 on 2024-12-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='score',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
